import { Project, SimulationResult, StatsData } from "./types";

export const statsData: StatsData = {
  projectsMonitored: 24,
  riskAlerts: 7,
  expectedAnnualLoss: 184500000,
  activeSimulations: 3,
};

export const mockProjects: Project[] = [
  {
    id: "proj-001",
    name: "Mumbai Coastal Defence",
    location: { type: "Point", coordinates: [72.8777, 19.076], city: "Mumbai", state: "Maharashtra" },
    hazardType: "Flood",
    riskScore: 87,
    riskLevel: "High",
    expectedAnnualLoss: 45000000,
    projectCost: 120000000,
    recommendations: ["Elevate critical infrastructure", "Install flood barriers", "Improve drainage systems"],
    createdBy: "user-001",
    createdAt: new Date("2025-08-15"),
    lastRunAt: new Date("2026-02-10"),
    status: "Active",
  },
  {
    id: "proj-002",
    name: "Chennai Heat Resilience",
    location: { type: "Point", coordinates: [80.2707, 13.0827], city: "Chennai", state: "Tamil Nadu" },
    hazardType: "Heat",
    riskScore: 72,
    riskLevel: "High",
    expectedAnnualLoss: 32000000,
    projectCost: 85000000,
    recommendations: ["Urban green corridors", "Cool roof mandates", "Early warning systems"],
    createdBy: "user-001",
    createdAt: new Date("2025-09-22"),
    lastRunAt: new Date("2026-02-08"),
    status: "Active",
  },
  {
    id: "proj-003",
    name: "Delhi NCR Storm Shield",
    location: { type: "Point", coordinates: [77.1025, 28.7041], city: "New Delhi", state: "Delhi" },
    hazardType: "Storm",
    riskScore: 58,
    riskLevel: "Medium",
    expectedAnnualLoss: 28000000,
    projectCost: 95000000,
    recommendations: ["Reinforce power grid", "Storm-resistant building codes", "Emergency shelters"],
    createdBy: "user-001",
    createdAt: new Date("2025-11-05"),
    lastRunAt: new Date("2026-01-28"),
    status: "Active",
  },
  {
    id: "proj-004",
    name: "Kolkata Flood Mapping",
    location: { type: "Point", coordinates: [88.3639, 22.5726], city: "Kolkata", state: "West Bengal" },
    hazardType: "Flood",
    riskScore: 65,
    riskLevel: "Medium",
    expectedAnnualLoss: 38000000,
    projectCost: 72000000,
    recommendations: ["Wetland restoration", "Pump station upgrades", "Flood-proof housing"],
    createdBy: "user-001",
    createdAt: new Date("2025-12-01"),
    lastRunAt: new Date("2026-02-15"),
    status: "Active",
  },
  {
    id: "proj-005",
    name: "Bengaluru Water Table",
    location: { type: "Point", coordinates: [77.5946, 12.9716], city: "Bengaluru", state: "Karnataka" },
    hazardType: "Flood",
    riskScore: 41,
    riskLevel: "Low",
    expectedAnnualLoss: 15000000,
    projectCost: 55000000,
    recommendations: ["Lake rejuvenation", "Rainwater harvesting mandates", "Permeable pavements"],
    createdBy: "user-001",
    createdAt: new Date("2026-01-10"),
    lastRunAt: new Date("2026-02-12"),
    status: "Active",
  },
  {
    id: "proj-006",
    name: "Ahmedabad Heat Action",
    location: { type: "Point", coordinates: [72.5714, 23.0225], city: "Ahmedabad", state: "Gujarat" },
    hazardType: "Heat",
    riskScore: 34,
    riskLevel: "Low",
    expectedAnnualLoss: 12000000,
    projectCost: 40000000,
    recommendations: ["Shade structures", "Public cooling centers", "Heat-tolerant vegetation"],
    createdBy: "user-001",
    createdAt: new Date("2026-01-20"),
    lastRunAt: new Date("2026-02-14"),
    status: "Active",
  },
];

export const mockSimulationResult: SimulationResult = {
  id: "sim-001",
  projectId: "proj-001",
  scenarioYear: 2050,
  hazardType: "Flood",
  budget: 50000000,
  riskScore: 73,
  expectedAnnualLoss: 38500000,
  roiPercent: 245,
  recommendations: [
    "Deploy AI-powered early flood warning system across 12 coastal zones",
    "Construct elevated transit corridors connecting critical infrastructure nodes",
    "Install smart drainage with IoT sensors in 8 high-risk catchment areas",
    "Implement nature-based solutions: mangrove restoration across 15km coastline",
    "Upgrade stormwater pumping capacity by 340% in priority districts",
  ],
  createdAt: new Date("2026-02-18"),
};
